name: Bug Report
description: Create a bug report to help us improve the game.
labels: "Type: Bug"
assignees: []
body:
- type: textarea
  id: bug-report
  attributes:
    label: Bug Report
    description: Please be as descriptive as possible in your bug report.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: Please explain what the desired behavior is.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: Please provide step by step instructions on what we need to do to reproduce this bug.
  validations:
    required: true

- type: input
  id: server-version
  attributes:
    label: BYOND Server Version
    description: What version of BYOND is running on the server?
    placeholder: "514.1566"

- type: input
  id: client-version
  attributes:
    label: BYOND Client Version
    description: What version of BYOND is running on the client?
    placeholder: "514.1566"
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Error Logs
    description: Drag and drop an error log or copy and paste any relavent error messages.
    render: shell

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Drag and drop or copy and paste any relavent screenshots.

- type: checkboxes
  id: form-completion
  attributes:
    label: Form Completion and Accuracy
    description: By submitting this issue, you confirm that this form has been completed in full and is accurate to the best of your knowledge.
    options:
      - label: I confirm that this form has been completed in full and is accurate to the best of my knowledge.
        required: true