blank_issues_enabled: false
contact_links:
  - name: BYOND Hub
    url: https://www.byond.com/games/IllusiveBlair/NarutoEvolution
    about: Be sure to become a fan of the official BYOND Hub to know when the servers are online!

  - name: Community Forums
    url: https://community.narutoevolution.com
    about: Join our official community forums.

  - name: Community Wiki
    url: https://wiki.narutoevolution.com
    about: Have a look at the official wiki for more game related information.
    
  - name: Discord Server
    url: https://discord.gg/pweBQzuJnZ
    about: Join our official Discord server.