blank_issues_enabled: false
contact_links:
  - name: Community Forums
    url: https://community.narutoevolution.com
    about: Join our community forums!
  - name: Community Wiki
    url: https://wiki.narutoevolution.com
    about: Have a look at the Naruto Evolution Wiki for more game related information.